use crate::utils::system::{assert_root, create_file};
use log::info;
use std::process::Command;

// No longer needed: all privileged operations are now handled by the lapctld daemon via D-Bus.
const LAPCTL_UDEV_RULES: &str = "# lapctl udev rules (placeholder)\n";

const POLKIT_POLICY: &str = r#"<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE policyconfig PUBLIC
 "-//freedesktop//DTD PolicyKit Policy Configuration 1.0//EN"
 "http://www.freedesktop.org/standards/PolicyKit/1/policyconfig.dtd">
<policyconfig>
  <vendor>lapctl</vendor>
  <vendor_url>https://github.com/S4NKALP/lapctl</vendor_url>
  <action id="org.lapctl.execute">
    <description>Elevated execution for lapctl</description>
    <message>Authentication is required to perform privileged lapctl operations</message>
    <defaults>
      <allow_any>auth_admin</allow_any>
      <allow_inactive>auth_admin</allow_inactive>
      <allow_active>yes</allow_active>
    </defaults>
    <annotate key="org.freedesktop.policykit.exec.path">/usr/bin/lapctl</annotate>
    <annotate key="org.freedesktop.policykit.exec.allow_gui">false</annotate>
  </action>
</policyconfig>
"#;

const POLKIT_RULES: &str = r#"/* /etc/polkit-1/rules.d/10-lapctl.rules
 * Automatically generated by lapctl
 * This rule allows users in the 'wheel' or 'sudo' groups to
 * perform privileged lapctl operations via pkexec without a password.
 */
polkit.addRule(function(action, subject) {
    if (action.id == "org.freedesktop.policykit.exec" &&
        action.lookup("program").indexOf("lapctl") !== -1 &&
        (subject.isInGroup("wheel") || subject.isInGroup("sudo"))) {
        return polkit.Result.YES;
    }
});
"#;

const DBUS_POLICY: &str = r#"<!DOCTYPE busconfig PUBLIC
          "-//freedesktop//DTD D-BUS Bus Configuration 1.0//EN"
          "http://www.freedesktop.org/standards/dbus/1.0/busconfig.dtd">
<busconfig>
    <policy user="root">
        <allow own="org.lapctl"/>
        <allow send_destination="org.lapctl"/>
        <allow receive_sender="org.lapctl"/>
    </policy>
    <policy group="wheel">
        <allow send_destination="org.lapctl"/>
        <allow receive_sender="org.lapctl"/>
    </policy>
    <policy group="sudo">
        <allow send_destination="org.lapctl"/>
        <allow receive_sender="org.lapctl"/>
    </policy>
</busconfig>
"#;

const SYSTEMD_SERVICE: &str = r#"[Unit]
Description=lapctl hardware management daemon
After=dbus.service

[Service]
Type=simple
ExecStart=/usr/bin/lapctl daemon
Restart=on-failure

[Install]
WantedBy=multi-user.target
"#;

pub fn execute() {
    assert_root();

    println!("Installing lapctl configuration for daemon communication...");

    let dbus_policy_path = "/etc/dbus-1/system.d/org.lapctl.conf";
    create_file(dbus_policy_path, DBUS_POLICY, false);

    let service_path = "/etc/systemd/system/lapctld.service";
    create_file(service_path, SYSTEMD_SERVICE, false);

    // Also install the udev rules file (even if empty now) to avoid errors if it was previously there
    let rules_path = "/etc/udev/rules.d/99-lapctl.rules";
    create_file(rules_path, LAPCTL_UDEV_RULES, false);

    // Polkit fallbacks for rootless execution without the daemon
    let polkit_policy_path = "/usr/share/polkit-1/actions/org.lapctl.policy";
    create_file(polkit_policy_path, POLKIT_POLICY, false);

    let polkit_rules_path = "/etc/polkit-1/rules.d/10-lapctl.rules";
    create_file(polkit_rules_path, POLKIT_RULES, false);

    println!("Successfully installed configuration files.");
    println!("Activating background daemon (lapctld)...");

    // Reload systemd to recognize the new service
    let _ = Command::new("systemctl").arg("daemon-reload").status();

    // Enable and start the daemon
    let status = Command::new("systemctl")
        .args(["enable", "--now", "lapctld"])
        .status();

    if let Ok(s) = status {
        if s.success() {
            info!("lapctld daemon enabled and started.");
        } else {
            log::error!("Failed to enable/start lapctld daemon.");
        }
    }

    println!("Installation successful! The lapctld daemon is now running.");
    println!("You can now use all lapctl commands without sudo.");
}
