use crate::utils::system::{assert_root, create_file};
use log::info;
use std::process::Command;

const LAPCTL_UDEV_RULES: &str = r#"# /etc/udev/rules.d/99-lapctl.rules
# Automatically generated by lapctl
# This file grants read/write permissions to all local users 
# for the SysFS endpoints required by lapctl's power, cooling, and battery commands.

# ACPI Platform Profiles & CPU Scaling
ACTION=="add", SUBSYSTEM=="firmware", RUN+="/bin/sh -c 'chmod a+w /sys/firmware/acpi/platform_profile 2>/dev/null'"
ACTION=="add", SUBSYSTEM=="cpu", RUN+="/bin/sh -c 'chmod a+w /sys/devices/system/cpu/cpu*/cpufreq/scaling_governor 2>/dev/null'"
ACTION=="add", SUBSYSTEM=="cpu", RUN+="/bin/sh -c 'chmod a+w /sys/devices/system/cpu/cpu*/cpufreq/energy_performance_preference 2>/dev/null'"

# Battery Charging Limits
ACTION=="add", SUBSYSTEM=="power_supply", RUN+="/bin/sh -c 'chmod a+w /sys/class/power_supply/BAT*/charge_control_end_threshold 2>/dev/null'"

# Lenovo Ideapad Thermal and Conservation Mode
ACTION=="add", SUBSYSTEM=="platform", RUN+="/bin/sh -c 'chmod a+w /sys/bus/platform/drivers/ideapad_acpi/VPC*/fan_mode 2>/dev/null'"
ACTION=="add", SUBSYSTEM=="platform", RUN+="/bin/sh -c 'chmod a+w /sys/bus/platform/drivers/ideapad_acpi/VPC*/conservation_mode 2>/dev/null'"

# ASUS WMI Thermal Policy
ACTION=="add", SUBSYSTEM=="platform", RUN+="/bin/sh -c 'chmod a+w /sys/devices/platform/asus-nb-wmi/throttle_thermal_policy 2>/dev/null'"

# Intel RAPL TDP Control
ACTION=="add", SUBSYSTEM=="powercap", RUN+="/bin/sh -c 'chmod a+w /sys/class/powercap/intel-rapl:0/constraint_*_power_limit_uw 2>/dev/null'"

# AMD HWMon Power Capping
ACTION=="add", SUBSYSTEM=="hwmon", RUN+="/bin/sh -c 'find /sys/class/hwmon -name \"power1_cap\" -exec chmod a+w {} + 2>/dev/null'"

# Input Device Inhibition (Touchpad)
ACTION=="add", SUBSYSTEM=="input", RUN+="/bin/sh -c 'find /sys/class/input -name \"inhibited\" -exec chmod a+w {} + 2>/dev/null'"
"#;

pub fn execute() {
    assert_root();

    println!("Installing lapctl udev rules for rootless hardware configuration...");

    let rules_path = "/etc/udev/rules.d/99-lapctl.rules";
    create_file(rules_path, LAPCTL_UDEV_RULES, false);

    println!("Successfully wrote rules to {}", rules_path);
    println!("Loading rules and applying immediate session permissions...");

    let _ = Command::new("udevadm")
        .args(["control", "--reload-rules"])
        .status();

    let _ = Command::new("udevadm").args(["trigger"]).status();

    // The udevadm trigger often fails to catch already-initialized ACPI nodes without a reboot,
    // so we manually apply the permissions for the current session right now.
    let commands = vec![
        "chmod a+w /sys/firmware/acpi/platform_profile 2>/dev/null",
        "chmod a+w /sys/devices/system/cpu/cpu*/cpufreq/scaling_governor 2>/dev/null",
        "chmod a+w /sys/devices/system/cpu/cpu*/cpufreq/energy_performance_preference 2>/dev/null",
        "chmod a+w /sys/class/power_supply/BAT*/charge_control_end_threshold 2>/dev/null",
        "chmod a+w /sys/bus/platform/drivers/ideapad_acpi/VPC*/fan_mode 2>/dev/null",
        "chmod a+w /sys/bus/platform/drivers/ideapad_acpi/VPC*/conservation_mode 2>/dev/null",
        "chmod a+w /sys/devices/platform/asus-nb-wmi/throttle_thermal_policy 2>/dev/null",
        "chmod a+w /sys/class/powercap/intel-rapl:0/constraint_*_power_limit_uw 2>/dev/null",
        "find /sys/class/hwmon -name \"power1_cap\" -exec chmod a+w {} + 2>/dev/null",
        "find /sys/class/input -name \"inhibited\" -exec chmod a+w {} + 2>/dev/null",
    ];

    for cmd in commands {
        let _ = Command::new("sh").arg("-c").arg(cmd).status();
    }

    info!("Udev reload and immediate ACL application complete.");
    println!(
        "Installation successful! You can now use lapctl power, cooling, and battery commands without sudo."
    );
}
